#include <cstdint>

class cpu_instructions {
    public:
        // 8-bit instructions
        // 0x00                 // 0x01                  // 0x02                  // 0x03                 // 0x04                    // 0x05                   // 0x06                   // 0x07                 // 0x08                    // 0x09                  // 0x0A                  // 0x0B                // 0x0C                    // 0x0D                  // 0x0E                  // 0x0F
        static void NOP();      static void LD_BC_d16(); static void LD_pBC_A();  static void INC_BC();   static void INC_B();       static void DEC_B();      static void LD_B_d8();    static void RLCA();     static void LD_pa16_SP();  static void ADD_HL_BC(); static void LD_A_pBC();  static void DEC_BC();  static void INC_C();       static void DEC_C();     static void LD_C_d8();   static void RRCA();    // 0x
        static void STOP();     static void LD_DE_d16(); static void LD_pDE_A();  static void INC_DE();   static void INC_D();       static void DEC_D();      static void LD_D_d8();    static void RLA();      static void JR_r8();       static void ADD_HL_DE(); static void LD_A_pDE();  static void DEC_DE();  static void INC_E();       static void DEC_E();     static void LD_E_d8();   static void RRA();     // 1x
        static void JR_NZ_s8(); static void LD_HL_d16(); static void LD_pHLp_A(); static void INC_HL();   static void INC_H();       static void DEC_H();      static void LD_H_d8();    static void DAA();      static void JR_Z_s8();     static void ADD_HL_HL(); static void LD_A_pHLp(); static void DEC_HL();  static void INC_L();       static void DEC_L();     static void LD_L_d8();   static void CPL();     // 2x
        static void JR_NC_s8(); static void LD_SP_d16(); static void LD_pHLm_A(); static void INC_SP();   static void INC_pHL();     static void DEC_pHL();    static void LD_pHL_d8();  static void SCF();      static void JR_C_s8();     static void ADD_HL_SP(); static void LD_A_pHLm(); static void DEC_SP();  static void INC_A();       static void DEC_A();     static void LD_A_d8();   static void CCF();     // 3x
        static void LD_B_B();   static void LD_B_C();    static void LD_B_D();    static void LD_B_E();   static void LD_B_H();      static void LD_B_L();     static void LD_B_pHL();   static void LD_B_A();   static void LD_C_B();      static void LD_C_C();    static void LD_C_D();    static void LD_C_E();  static void LD_C_H();      static void LD_C_L();    static void LD_C_pHL();  static void LD_C_A();  // 4x
        static void LD_D_B();   static void LD_D_C();    static void LD_D_D();    static void LD_D_E();   static void LD_D_H();      static void LD_D_L();     static void LD_D_pHL();   static void LD_D_A();   static void LD_E_B();      static void LD_E_C();    static void LD_E_D();    static void LD_E_E();  static void LD_E_H();      static void LD_E_L();    static void LD_E_pHL();  static void LD_E_A();  // 5x
        static void LD_H_B();   static void LD_H_C();    static void LD_H_D();    static void LD_H_E();   static void LD_H_H();      static void LD_H_L();     static void LD_H_pHL();   static void LD_H_A();   static void LD_L_B();      static void LD_L_C();    static void LD_L_D();    static void LD_L_E();  static void LD_L_H();      static void LD_L_L();    static void LD_L_pHL();  static void LD_L_A();  // 6x
        static void LD_pHL_B(); static void LD_pHL_C();  static void LD_pHL_D();  static void LD_pHL_E(); static void LD_pHL_H();    static void LD_pHL_L();   static void HALT();       static void LD_pHL_A(); static void LD_A_B();      static void LD_A_C();    static void LD_A_D();    static void LD_A_E();  static void LD_A_H();      static void LD_A_L();    static void LD_A_pHL();  static void LD_A_A();  // 7x
        static void ADD_A_B();  static void ADD_A_C();   static void ADD_A_D();   static void ADD_A_E();  static void ADD_A_H();     static void ADD_A_L();    static void ADD_A_pHL();  static void ADD_A_A();  static void ADC_A_B();     static void ADC_A_C();   static void ADC_A_D();   static void ADC_A_E(); static void ADC_A_H();     static void ADC_A_L();   static void ADC_A_pHL(); static void ADC_A_A(); // 8x
        static void SUB_B();    static void SUB_C();     static void SUB_D();     static void SUB_E();    static void SUB_H();       static void SUB_L();      static void SUB_pHL();    static void SUB_A();    static void SBC_A_B();     static void SBC_A_C();   static void SBC_A_D();   static void SBC_A_E(); static void SBC_A_H();     static void SBC_A_L();   static void SBC_A_pHL(); static void SBC_A_A(); // 9x
        static void AND_B();    static void AND_C();     static void AND_D();     static void AND_E();    static void AND_H();       static void AND_L();      static void AND_pHL();    static void AND_A();    static void XOR_B();       static void XOR_C();     static void XOR_D();     static void XOR_E();   static void XOR_H();       static void XOR_L();     static void XOR_pHL();   static void XOR_A();   // Ax
        static void OR_B();     static void OR_C();      static void OR_D();      static void OR_E();     static void OR_H();        static void OR_L();       static void OR_pHL();     static void OR_A();     static void CP_B();        static void CP_C();      static void CP_D();      static void CP_E();    static void CP_H();        static void CP_L();      static void CP_pHL();    static void CP_A();    // Bx
        static void RET_NZ();   static void POP_BC();    static void JP_NZ_a16(); static void JP_a16();   static void CALL_NZ_a16(); static void PUSH_BC();    static void ADD_A_d8();   static void RST_0();    static void RET_Z();       static void RET();       static void JP_Z_a16();  /* EMPTY */            static void CALL_Z_a16();  static void CALL_a16();  static void ADC_A_d8();  static void RST_1();   // Cx
        static void RET_NC();   static void POP_DE();    static void JP_NC_a16(); /* EMPTY */             static void CALL_NC_a16(); static void PUSH_DE();    static void SUB_d8();     static void RST_2();    static void RET_C();       static void RETI();      static void JP_C_a16();  /* EMPTY */            static void CALL_C_a16();  /* EMPTY */              static void SBC_A_d8();  static void RST_3();   // Dx
        static void LD_pa8_A(); static void POP_HL();    static void LDH_pC_A();  /* EMPTY */             /* EMPTY */                static void PUSH_HL();    static void AND_d8();     static void RST_4();    static void ADD_SP_s8();   static void JP_HL();     static void LD_pa16_A(); /* EMPTY */            /* EMPTY */                /* EMPTY */              static void XOR_d8();    static void RST_5();   // Ex
        static void LD_A_pa8(); static void POP_AF();    static void LD_A_pC();   static void DI();       /* EMPTY */                static void PUSH_AF();    static void OR_d8();      static void RST_6();    static void LD_HL_SPps8(); static void LD_SP_HL();  static void LD_A_pa16(); static void EI();      /* EMPTY */                /* EMPTY */              static void CP_d8();     static void RST_7();   // Fx




        // 16-bit instructions (0xCB prefix)
};